### ISSUE TITLE
Scenariolink plugin

### ISSUE THREAD

**Issue by MMahdi97** [LCA-ActivityBrowser/activity-browser#1311]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

I have installed AB and added the scenariolink plugin, but I cannot add this plugin to the AB
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/bee7d97e-5ffb-4c07-81af-b7f0eda887fa)
I select it and then confirm, but I cannot still see the scenariolink in the tool bar.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/08b6112a-bec3-4e13-9435-e5427a57afd1)

### Operating system

Windows 10

**Comment by romainsacchi** [comment]
Hi @MMahdi97, which version of AB do you have?
Also, what does it say in your conda terminal after activating the plugin?

**Comment by MMahdi97** [comment]
Hi @romainsacchi, the version I am using is 2.9.7

The following text is shown after activating the plugin:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/366bd50f-208c-4bc6-8116-b4477d17ac91)

**Comment by marc-vdm** [comment]
@MMahdi97 Could you show the entire conda terminal from the moment you press enter after writing `activity-browser`? I think we're missing some information.

**Comment by MMahdi97** [comment]
Here is the entire conda terminal
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/4d2bea35-04bc-4ab8-93be-9aff3c04e449)
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/c800b436-416e-408f-9471-9566b5a2bc2b)
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/c46948a5-6941-4e1c-996b-3e13567b4d54)

**Comment by marc-vdm** [comment]
thanks, could you also share the output of `conda list` please?

@romainsacchi Something seems to be going wrong in `unfold` if I read this correctly? about 1/4 of the way, before `--- Logging error ---`

**Comment by MMahdi97** [comment]
Sure.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/35abadb7-6fd7-4823-9103-fec654fe5d02)
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/969793c5-7e19-4788-8b03-79cfa947c580)
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/44f740f8-2bb9-451f-811b-402ba72a1ec9)
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/4c4d83f8-f83e-47dd-a025-0820f8993e6e)

**Comment by marc-vdm** [comment]
@romainsacchi This seems to be quite an old unfold version. Do you know if that's correct?

**Comment by marc-vdm** [comment]
I'm closing this as issue for Unfold. Hopefully the new version of Activity Browser released soon (`2.10.1`) and Scenario Link version related to this should fix this.

**Comment by MMahdi97** [comment]
Hello Marc, Romain,
Now I am using Activity Browser version 2.10.1, but I still have the same problem!
![image](https://github.com/user-attachments/assets/dda9cf8c-d5ce-4e23-b460-4095f1c3aa14)

Here is the error:

![image](https://github.com/user-attachments/assets/ca1f755b-872d-4967-a1a8-208c85c69879)


I would appreciate it if you help me with this issue.
