### ISSUE TITLE
Export LCA scores

### ISSUE THREAD

**Issue by rafaellaurenti** [LCA-ActivityBrowser/activity-browser#164]
Hi again =)

As we talked at the IEGRC, it'd be nice to be able to export the LCA scores to a CSV file. Alternatively, it'd be great to copy the activity names and impact category to the clipboard together with the respective score. Currently, I just get the score when I do it. It'b be useful when having many activities and impact categories in the calculations.

THANKS A LOT!
Rafael

![image](https://user-images.githubusercontent.com/39736183/40666754-c85e2510-6360-11e8-8f62-608f9f3a6f1f.png)
![image](https://user-images.githubusercontent.com/39736183/40666791-defb4b4a-6360-11e8-9d8c-1282cc13882e.png)

**Comment by haasad** [comment]
Hi Rafael,

I had a go at this and pushed this just now. You can get the new features with `conda update activity-browser-dev`. Let me know what you think.

**Comment by rafaellaurenti** [comment]
Hi Adrian,

Thank you. I tried but couldn't find the option to export. Also copy and paste still not coping the activity names. 
I wonder if my update didn't work properly. I ran the command but got this message:

![image](https://user-images.githubusercontent.com/39736183/40828314-8d8adae2-6580-11e8-8b84-9903c9c56360.png)

Thank you.

**Comment by haasad** [comment]
Hey, it looks like something went wrong with the upload of the new version. Sorry about that. It should work now. Please try updating again.

If it worked you should have new buttons below the results table:
![image](https://user-images.githubusercontent.com/11636405/40833265-b413a182-658d-11e8-9f22-700cc47b963c.png)

**Comment by rafaellaurenti** [comment]
Hi, the command updated the version but I don't still get the new buttons. Maybe I'm doing something wrong?

**Comment by haasad** [comment]
Could you maybe check the output of `conda list` and check what version is installed? For me it looks like this:
```
# packages in environment at /home/adrian/miniconda3/envs/aaa:
#
# Name                    Version                   Build  Channel
activity-browser-dev      2.2.4.dev       py_201806010907    haasad
...etc
```
Otherwise there might also be some confusion with the conda environments. In case you followed the installation instructions you should have an environment called `ab`, whereas in your screenshot from above you seem to be working in the `base` environment. You can switch the envs with `conda activate ab` and then update inside the environment.

**Comment by rafaellaurenti** [comment]
Ahhh ok. At my ab environment I have version 2.2.4 build py_1 but in the base I have the dev one. I didn't know have the activity-browser also installed in the base. I can see the new buttons when I run ab at the base. Thanks a lot! I had probably messed up the environments when I installed the software. Sorry about the confusion.

For some unknown reason I can't run the update in the ab environment but will try to uninstall things and install again properly.
![image](https://user-images.githubusercontent.com/39736183/40847607-25642300-65bd-11e8-831f-5544ecb9b912.png)


Thank you very much for your time.
