### ISSUE TITLE
[MacOS] No graph view/Sankey

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#522]
When opening graph view this error is thrown: 

```
[5372:44807:0210/105819.518910:ERROR:gl_context_cgl.cc(136)] Error creating context.

[5372:44807:0210/105819.518945:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
```

MacOS version: 10.14.6 Mojave
<img width="1435" alt="Screenshot 2021-02-10 at 11 10 14 AM" src="https://user-images.githubusercontent.com/34626062/107500141-bc618300-6b8d-11eb-8f96-87b418ff25b8.png">
<img width="590" alt="Screenshot 2021-02-10 at 11 10 26 AM" src="https://user-images.githubusercontent.com/34626062/107500146-bec3dd00-6b8d-11eb-93a4-96be81b7d574.png">

**Comment by bsteubing** [comment]
I can confirm this on a Windows PC... I think it is an old bug that came back that the graph only shows the second time you load something for the graph explorer...

**Comment by dgdekoning** [comment]
Should hopefully be resolved by #552.

**Comment by BenPortner** [comment]
@dgdekoning @bsteubing 
I have a student who still experiences this problem. AB does not show the welcome screen, sankey diagrams or graph view. The student is using the latest version of AB (2.6.7, installed yesterday via conda) on macOS Big Sur version 11.6.

Console log:

```
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/6382cdab-9715-4107-a1f6-249e9cc7e95f
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
qt.qpa.drawing: Layer-backing can not be explicitly controlled on 10.14 when built against the 10.14 SDK
Reset project settings directory to: /Users/student/Library/Application Support/Brightway3/default.c21f969b5f03d33d43e04f8f136e7682
Loading user settings:
dirpath already loaded
Brightway2 data directory: /Users/student/Library/Application Support/Brightway3
Brightway2 active project: default
Qt Version: 5.12.9
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
[50875:84483:0112/154516.165964:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.166559:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.175598:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.175646:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.182426:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.182890:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.186321:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.186359:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.380387:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.380421:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.566349:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.566421:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.583511:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.583561:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.585011:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.585089:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.623790:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.623839:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[50875:84483:0112/154516.625031:ERROR:gl_context_cgl.cc(136)] Error creating context.
[50875:84483:0112/154516.625075:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
```

**Comment by dgdekoning** [comment]
@BenPortner, I am guessing your student uses a macbook with the latest version of ~Big Sur~ Monterey.

The fix I mentioned earlier only checks for the earliest version of Big Sur, so it will have to be updated to include the newer version. Or resolved some other way.

**Comment by BenPortner** [comment]
@dgdekoning Thank you for your answer. As written in my original comment, the problem occurs on Big Sur version 11.6. I cannot say whether it occurs on Monterey.

**Comment by marc-vdm** [comment]
Closing as stale

**Comment by exuexex** [comment]
Hello,
I have the same problem. I use windows and I have the last update of AB. 
<img width="395" alt="Screenshot 2024-11-15 111606" src="https://github.com/user-attachments/assets/402b6443-d2cc-470f-8c78-f5105a724ea3">
